### PR TITLE
Add a shadow to ÜberCharge percentage label

### PR DESCRIPTION
**Pull request by camwright**

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Does this work with when you have the Vaccinator equipped? Usually because it doesn't use the usual Uber percentage the shadow label doesn't get hidden.

**Comment by camwright** [comment]
No, it doesn't apparently. I don't know too much about how HUDs work. How does TF2 hide `ChargeLabel` when the Vaccinator is equipped? I assumed it just set `#TF_UberchargeMinHUD` to an empty string.

**Comment by CriticalFlaw** [comment]
Maybe the trick is to pin the shadow to the label. Add the highlighted code to your `ChargeLabelShadow`, then change the xpos and ypos to -2. Maybe then if `ChargeLabel` disappears, so will the shadow label.

image

**Comment by camwright** [comment]
I already tried that actually thinking the same thing. I actually copied in the entire ahud implementation and couldn't get it to work. I even tried moving the Vaccinator's resist icon to cover the shadow, which I honestly think looks better than its current position anyway, but when switching to the saw the resist icon disappears and you can still see the shadow.

**Comment by CriticalFlaw** [comment]
The best thing to do would be to redesign the ubercharge meter to either be behind the percentage like how ahud has it or put the percentage above the meter like in flawhud. Either way I think many players would complain about the redesign because it's been the way it is for so long.

Ultimately, I think we may have to drop and forget about this change.

**Pull request closed without merging**
