### PR TITLE
Fix Competitive MMR not displaying

### PR DESCRIPTION
**Pull request by piman51277**
The fix to Issue https://github.com/raysfire/rayshud/issues/98 was reverted later, causing the bug to occur again.

This reverts relevant values back to 
https://github.com/raysfire/rayshud/commit/14912d2b2e8f6f14b58731cf3c1e1afde4574ffc

Current:

Reversion:

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Do the competitive stats still display properly in the matchmaking dashboard?

**Comment by piman51277** [comment]
Now I check, they ended up being a little too high up. I'll work out a fix for that in a sec.

**Comment by piman51277** [comment]
I fixed the issue, and there is no longer a problem with menus / stats

**Comment by CriticalFlaw** [comment]
Nice work. I'll test it out later tonight then will merge it in.

**Comment by CriticalFlaw** [comment]
image

When viewing the casual badge, the XP label is over lapping with the level label because it and the MMR label are one and the same. Ideally it should be designed in a way where it looks good with both badge types.

**Comment by piman51277** [comment]
That should hide the extra casual text, and leave MMR intact

**Comment by CriticalFlaw** [comment]
That's not ideal either because you're just removing the XP label altogether from the casual badge. Best thing to do is to edit just the MMR label via `pvpcomprankpanel.res`. Create a file in `resource/ui` with that name, put in the below contents and undo all of your changes made to `pvprankpanel.res`. Test that out and if it works add it to the PR.

```
#base "PvPRankPanel.res"

"Resource/UI/PvPRankPanel.res"
{
	"BGPanel"
	{
		"StatsContainer"
		{
			"visible"		"1"

			"XPBar"
			{
				"ypos"	"20"
				"alpha"	"100"

				"CurrentXPLabel"
				{
					"xpos"			"15"
					"ypos"			"rs1-20"
					"wide"			"140"
					"textAlignment"	"center"
					"visible"		"1"

					disabled_mini
					{
						"xpos"			"cs-0.5"
						"textAlignment"	"center"
					}
				}

				"NextLevelXPLabel"
				{
					"visible"		"0"
				}

				"ProgressBarsContainer"
				{
					"visible"		"0"
				}
			}
		}
	}
}
```

**Comment by piman51277** [comment]
It works!

**Review by CriticalFlaw — APPROVED** [review]

**Comment by CriticalFlaw** [comment]
Merged. Thank you for investigating

**Pull request merged**
