### PR TITLE
Added automatic installers for mac OSx and Linux

### PR DESCRIPTION
**Pull request by J-tt**
A lot of room for improvement (such as customisation and better way of installing git on linux).

### CODE REVIEW

**Comment by J-tt** [comment]
Added Windows support

**Comment by Gonzih** [comment]
Why not just do git clone from this repo?

**Comment by J-tt** [comment]
That's basically what this does. It installs git, asks for a location, and
then clones it.

**Comment by Gonzih** [comment]
Oh, I see. Why not add script also to this repo then?

**Comment by J-tt** [comment]
Then the script would get cloned, which is unnecessary.

**Pull request closed without merging**
